version: '3'
services:
  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql

  keycloak-w:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      # Same values as the mysql-kc service
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    depends_on:
      - mysql
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    depends_on:
      - keycloak-w
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  discovery-service:
    container_name: discovery-service
    build:
      context: services/system/discovery-service
      dockerfile: Dockerfile
    image: discovery-service:3.0
    ports:
      - 1111:1111
  apis-service:
    container_name: apis-service
    build:
      context: services/ecommerce/apis
      dockerfile: Dockerfile
    image: apis-service:3.0
    ports:
      - 8888:8888
    depends_on:
      - elasticsearch

volumes:
  keycloak-and-mysql-volume:










#  mysql:
#    container_name: mysql
#    image: mysql
#    ports:
#      - 9595:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=test123
#  keycloak:
#    container_name: keycloak
#    image: jboss/keycloak
#    ports:
#      - 8080:8080
#    environment:
#      - KEYCLOAK_USER=root
#      - KEYCLOAK_PASSWORD=root