spring:
  application:
    name: apis
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceApp
    password: test123
    username: root
  jpa:
    hibernate:
      ddl-auto: none


server:
  port: 8181

keycloak:
  auth-server-url: http://localhost:8080/
  bearer-only: true
  public-client: true
  realm: ecommerce
  resource: backend

eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/