spring:
  application:
    name: apis
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceApp
    password: test123
    username: root

  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8181